name: Docs

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
#  pull_request:
#    branches: [ master ]
#    types: [ closed ]
  workflow_dispatch:

permissions:
    contents: write

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
      - name: Check gh-pages versions
        uses: jannekem/run-python-script-action@v1
        id: script
        with:
          script: |
            import pathlib
            import re

            from packaging.version import parse, InvalidVersion
            
            current_version, path = parse("${{ github.ref_name }}"), "./"
            
            with pathlib.Path(path) as dir:
                for file in dir.iterdir():
                    if file.is_dir():
                        try:
                            last_version = parse(file.name)
                            if current_version <= last_version:
                                set_output('is_new_version_docs', 'false')
                                exit()

                        except InvalidVersion:
                            pass
            
            set_output('is_new_version_docs', 'true')
    outputs:
      is_new_version_docs: ${{ steps.script.outputs.is_new_version_docs }}

  docs-gen:
    needs: docs-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          pip install -e .
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/_build
      - name: Prepare doc tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "DOCS_TAG=docs-${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Delete old doc tag
        continue-on-error: true
        run: |
          git clone https://github.com/sammnnz/pymagic9.git
          cd pymagic9
          git remote set-url origin https://x-access-token:${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}@github.com/sammnnz/pymagic9.git
          git tag -d ${{ steps.prepare_tag.outputs.DOCS_TAG }}
          git push --force origin :refs/tags/${{ steps.prepare_tag.outputs.DOCS_TAG }}
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: true
          destination_dir: ./${{ github.ref_name }}
          force_orphan: false
          keep_files: true
          personal_token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
          tag_name: ${{ steps.prepare_tag.outputs.DOCS_TAG }}
          tag_message: 'Deployment ${{ steps.prepare_tag.outputs.DOCS_TAG }}'
      - name: Recreate redirect/index.html
        if: needs.docs-check.outputs.is_new_version_docs == 'true'
        uses: jannekem/run-python-script-action@v1
        id: script
        with:
          script: |
            import re
            
            path, pattern = "docs/redirect/index.html", re.compile(r"\{\s*%\s*latest-version\s*%\s*}")

            with open(path, "r", encoding="utf8") as file:
                content = pattern.sub("${{ github.ref_name }}", file.read())

            with open(path, "w+", encoding="utf8") as file:
                file.write(content)
      - name: Deploy redirect/index.html
        if: needs.docs-check.outputs.is_new_version_docs == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: true
          force_orphan: false
          keep_files: true
          personal_token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/redirect/
