name: Docs

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'

permissions:
    contents: write

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
      - name: Check gh-pages versions
        uses: jannekem/run-python-script-action@v1
        id: script
        with:
          script: |
            import pathlib
            import re

            from packaging.version import parse, InvalidVersion
            
            current_version, path = parse("${{ github.ref_name }}"), "./"
            
            with pathlib.Path(path) as dir:
                for file in dir.iterdir():
                    if file.is_dir():
                        try:
                            version = parse(file.name)
                            if current_version < version:
                                set_output('is_new_version_docs', 'false')
                                exit()

                        except InvalidVersion:
                            pass
            
            set_output('is_new_version_docs', 'true')
    outputs:
      is_new_version_docs: ${{ steps.script.outputs.is_new_version_docs }}

  docs-gen:
    needs: docs-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          pip install -e .
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: true
          destination_dir: ./${{ github.ref_name }}
          keep_files: false
          personal_token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
      - name: Deploy latest
        if: needs.docs-check.outputs.is_new_version_docs == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: true
          destination_dir: ./latest
          keep_files: false
          personal_token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
